version: "3.5"
services:
    database:
        image: mysql
        ports:
            - 3310:3306
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: db